### ISSUE TITLE
mounts_original

### ISSUE THREAD

**Issue by CPapadim** [Grim-/Outward.Mount#3]
Hi, I'm wondering if there's somewhere I can get this assetbundle for the ninedots mounts.  I was interested in testing the newer version of this mode and was able to compile it but I'm not sure where to get this file.

**Comment by Grim-** [comment]
Hi there,

 if you join the Outward modding discord (https://discord.com/invite/zKyfGmy7TR), the Mount Mod has its own channel and the latest beta version is in the pins if you can't find it ask in general chat, this also includes all the mount bundles, if you read the documentation at https://github.com/Grim-/Outward.Mount/blob/main/docs/Creating%20your%20own%20mount.md you can also see the process for making your own.
